id: P009148
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:18.836696
source_metadata:
  id: bdr:W1KG9036
  title: རྒྱུད་བླ་མའི་འགྲེལ་པ།
  author: ''
  volumes:
    ff40d4ef8131431fb19976ae2554c1de:
      image_group_id: I1KG9064
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
