id: P009148
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9036
  title: རྒྱུད་བླ་མའི་འགྲེལ་པ།
  author: ''
  volumes:
    ff40d4ef8131431fb19976ae2554c1de:
      image_group_id: I1KG9064
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
